### ISSUE TITLE
Port Material JS to C#

### ISSUE THREAD

**Issue by galvesribeiro** [BlazorExtensions/BlazorMaterial#1]
Would be awesome if those components were independent of Google's Javascript.

We should investigate the feasibility of having all (or at least most of) the JS code ported to C#. It will depends on features exposed by Blazor.

**Comment by BenjaminCharlton** [comment]
What a fantastic idea! :+1:

**Comment by galvesribeiro** [comment]
I'm closing this issue as the work is being tracked on #7
