### ISSUE TITLE
Start office UI fabric repo

### ISSUE THREAD

**Issue by danielmeza** [BlazorExtensions/BlazorMaterial#2]
Hi folks! Will be awesome if you can make and office ui fabric repository I will start to implement it to Blazor and shared with you here

**Comment by galvesribeiro** [comment]
@danielmeza hey, thanks for reaching by.

It indeed would be awesome to have Office UI here.

Can you open this issue at the `Home` repo? We can keep talking about how it would work there. This repo is specific for Material design port.

See you there, thanks!
