### ISSUE TITLE
No Card support

### ISSUE THREAD

**Issue by masonwheeler** [BlazorExtensions/BlazorMaterial#3]
I'm trying to use BlazorMaterial in a project, but I've come to a point where I need a Card component, and this hasn't been added to the library yet.

**Comment by jan-johansson-mr** [comment]
Hi, I think the development has stopped on this repository. The code frequency tells it was an initial effort (I guess to create the repository), and then nothing has happened for more than 3 months. I too like material design, so I'd like to use it (material design) in my own work.

**Comment by masonwheeler** [comment]
In conversations with the author elsewhere,  he's told me he intends to continue working on it. This is mainly meant as a poke in the ribs, as it were, to prod him out of inactivity.

**Comment by galvesribeiro** [comment]
Hello,

The development not stopped nor this repo is abandoned. We just had other priorities on real work and for the community, other components like SignalR was a priority for the community, so I've put that on hold.

I'll return to it soon as I mentioned to @masonwheeler on Gitter, I just didn't had enough time for it.

We are two maintaining the majority of components here but we will make our best to get it out soon.

As always, we do appreciate PRs if you guys want to get it out faster.

I'll do my best to work on it soon. This is something I need for my other projects so bear with me that it will get out.

Thanks!

**Comment by GoranHalvarsson** [comment]
Yes great job guys. And we want the cards :)

**Comment by namanrajpal** [comment]
@galvesribeiro Are you entertaining pull requests?

**Comment by galvesribeiro** [comment]
Hello @namanrajpal absolutely!

I'm sorry to been so away... Still dealing with several work complications and didn't had much time to dedicate to the OSS projects last couple of months. If you want to evolve it faster than me, please open a PR and I'll be glad to review it.

Thanks!

**Comment by galvesribeiro** [comment]
Just a heads up. I'm slowly getting back to update all my OSS projects by first fixing issues and merging PRs. Will get back here eventually.

Hang on!

**Comment by enkodellc** [comment]
Check out MatBlazor, we have been building and adding components like cards.  https://github.com/BlazorComponents/MatBlazor

**Comment by galvesribeiro** [comment]
Hello @masonwheeler 

The work is being tracked now on #7 

Please expect good news earlier next month as I'm getting back from vacation.

Thanks!
