### ISSUE TITLE
Best way to use BlazorMaterial for a project

### ISSUE THREAD

**Issue by simonziegler** [BlazorExtensions/BlazorMaterial#6]
Gents,

Thank you for building this project, which I am keen to use for components in an upcoming project of mine. I am seeking your advice about how best to use BlazorMaterial. Is this a project that you intend to push towards open source contribution to complete the picture with other components (such as switches) and perhaps release in Nuget, or would you advise me to take a private copy and work with that?

Kind regards, Simon

**Comment by galvesribeiro** [comment]
Hello @simonziegler 

The intent is to pack it as nuget packages like the other repos on this org.

However, I didn't had time yet to finish the components but I would be very glad to take PRs from the community to help complete it so we can have it out as Nugets.

These packages need to be updated to latest Material releases/components and then implemented forward.

Feel free to send a PR if you want to speed up things and I'll be glad to review.

Thank you!

**Comment by jdebarochez** [comment]
Hello @galvesribeiro 

Do you have a list of the components you want first? We could imagine a big todo list and build a roadmap out of it.

Do you follow a workflow to implement the components?

**Comment by galvesribeiro** [comment]
We could get the material.io site, check the components, create a single issue to track all with a checkbox. Then whenever one start to work in a component, create a separated issue/PR and link to this main one

**Comment by simonziegler** [comment]
This is great - thank you. Unfortunately I'm not going to be much help building this thing :(

**Comment by galvesribeiro** [comment]
Hello folks. I'm going to close this issue as it is being tracked on #7
